# Generated by Django 3.2.11 on 2024-09-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_technical_specs'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_info',
            field=models.TextField(blank=True, verbose_name='Thông tin sản phẩm'),
        ),
    ]
