# Generated by Django 3.2.11 on 2024-09-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20240913_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='product_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
